vich_uploader:
    db_driver: orm

    metadata:
       type: attribute

    mappings:
        images_image:
            uri_prefix: /images/images
            upload_destination: '%kernel.project_dir%/public/images/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
